Prevent from erroring running the dev:test_data:create task
Otherwise, an error like this is thrown:

```
Writing issue trackers into backend

rake aborted!
NoMethodError: undefined method `id' for nil:NilClass

  after_commit { PopulateToSphinxJob.perform_later(id: bs_request.id, model_name: :bs_request) }
                                                                 ^^^
/obs/src/api/app/models/review.rb:77:in `block in <class:Review>'
<internal:kernel>:90:in `tap'
/obs/src/api/lib/tasks/dev.rake:162:in `block (4 levels) in <top (required)>'
/obs/src/api/lib/tasks/dev.rake:153:in `block (3 levels) in <top (required)>'
```