[api] Fix NameError: uninitialized constant error when accepting requests with autoaccept
Adds missing require, caused by 3d1db64c04d77e79f116b0e7a96e96bd41c92ee2

======

NameError: uninitialized constant BsRequest::AcceptRequestsJob

app/models/bs_request.rb:703→ block in change_review_state
activerecord-4.2.5.2/lib/active_record/locking/pessimistic.rb:72→ block in with_lock
activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ block in transaction
activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/transaction.rb:184→ within_new_transaction