[ci] Remove skipped tests
With the last minitest update skipped tests started to cause failures in
our travis test suite.

We have not touched these skipped tests since they were added. So it's
safe to say that we are not implementing them anytime soon.

Test failure:
  undefined method `test_cleanup_linking_projects' for class `Minitest::Result' (NameError)