Fix NameError in RoutesHelper::WebuiMatcher
The error was:
NameError: uninitialized constant RoutesHelper::WebuiMatcher::APIError

This is due to changes in how Zeitwerk works in Rails 6.1.x. It was fine
in Rails 6.0.x, although it was deprecated and there was a deprecation
warning.