Move sprockets-rails gem outside of assets group
This gem cannot be in the assets group since Sprockets is loaded in
config/application.rb. Without this change, the application doesn't boot
in the production environment due to this error:

LoadError: cannot load such file -- sprockets/railtie