[api] Enable ActiveRecord::Enum for user model
This has to be done in a separate step. Otherwise the migration would
fail, because rails would convert the stringified states to numbers.

=====

StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Truncated incorrect DOUBLE value: 'deleted': UPDATE `users` SET `users`.`new_state` = 0 WHERE `users`.`state` = 0
/vagrant/src/api/db/migrate/20170607105624_use_rails_enums_user_table.rb:8:in `block in up'