[frontend] Fix NoMethodError caused by missing module
Found when running some tests without using our VCR cassettes:

  NoMethodError:
    undefined method `new' for BsRequestAction::Differ::ForSource:Module
  Shared Example Group: "a full diff not requested for" called from ./spec/controllers/webui/request_controller_spec.rb:128
  # ./app/models/bs_request_action/differ.rb:8:in `sourcediff'
  # ./app/models/bs_request_action.rb:306:in `webui_infos'
  # ./app/models/bs_request.rb:1064:in `block in webui_actions'